<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'vendor/autoload.php'; // Path to the Composer autoload file

$mail = new PHPMailer(true);

//Server settings
$mail->isSMTP();
$mail->Host       = 'smtp.gmail.com'; // Set the SMTP server to send through
$mail->SMTPAuth   = true;               // Enable SMTP authentication
$mail->Username   = 'sevekasnanen81@gmail.com'; // SMTP username
$mail->Password   = 'Sever?317'; // SMTP password
$mail->SMTPSecure = 'ssl'; // Enable TLS encryption; 
$mail->Port       = 465; // TCP port to connect to

// Sender and reply-to address
$email = $_POST['email'];
$mail->setFrom($email, 'From Name');
$mail->addAddress('sevekasnanen81@gmail.com', 'recipient Name');

// Content
$mail->isHTML(false); // Set email format to HTML
$mail->Subject = $_POST['subject'];
$mail->Body = $_POST['message'];

if (!$mail->send()) {
    echo 'Message could not be sent. Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
} 
 


require 'path/to/composer/vendor/autoload.php'; // Ensure the path is correct

$mail = new PHPMailer(true); // Passing `true` enables exceptions

try {
    $mail->isSMTP();
    $mail->Host = 'live.smtp.mailtrap.io'; // Your SMTP server
    $mail->SMTPAuth = true;
    $mail->Username = 'paste one generated by Mailtrap'; // Your Mailtrap username
    $mail->Password = 'paste one generated by Mailtrap'; // Your Mailtrap password
    $mail->SMTPSecure = 'tls';
    $mail->Port = 2525;

    // Sender and recipient settings
    $mail->setFrom('info@mailtrap.io', 'Mailtrap');
    $mail->addReplyTo('info@mailtrap.io', 'Mailtrap');
    $mail->addAddress('recipient1@mailtrap.io', 'Tim'); // Primary recipient
    // CC and BCC
    $mail->addCC('cc1@example.com', 'Elena');
    $mail->addBCC('bcc1@example.com', 'Alex');
    // Adding more BCC recipients
    $mail->addBCC('bcc2@example.com', 'Anna');
    $mail->addBCC('bcc3@example.com', 'Mark');

    // Email content
    $mail->isHTML(true); // Set email format to HTML
    $mail->Subject = "PHPMailer SMTP test";
    $mail->Body = '<h1>Send HTML Email using SMTP in PHP</h1><p>This is a test email I\'m sending using SMTP mail server with PHPMailer.</p>'; // Example HTML body
    $mail->AltBody = 'This is the plain text version of the email content';

    if(!$mail->send()) {
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
    } else {
        echo 'Message has been sent';
    }
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
?>
